language: node_js
node_js:
- 7.5
cache:
- node_modules
before_install:
- npm install -g snazzy
before_script:
- node_modules/.bin/semistandard --verbose | snazzy
script:
- node_modules/karma/bin/karma start karma.conf.js --single-run
- cat ./coverage-lcov/lcov.info | node_modules/coveralls/bin/coveralls.js
